# Generated by Django 6.0.5 on 2026-05-16 08:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Q1', 'Q1 (July)'), ('Q2', 'Q2 (October)'), ('Q3', 'Q3 (January)'), ('Q4', 'Q4 (March/April)'), ('GOAL_SETTING', 'Goal Setting (May)')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2025)),
            ],
            options={
                'ordering': ['-year', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin/HR')], default='EMPLOYEE', max_length=20)),
                ('theme_preference', models.CharField(default='ocean', max_length=50)),
                ('unlocked_themes', models.JSONField(default=list)),
                ('performance_score', models.FloatField(default=0.0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thrust_area', models.CharField(choices=[('SALES', 'Sales & Revenue'), ('CUSTOMER', 'Customer Success'), ('PRODUCT', 'Product Development'), ('OPERATIONS', 'Operations Excellence'), ('PEOPLE', 'People & Culture'), ('FINANCE', 'Financial Management'), ('COMPLIANCE', 'Compliance & Risk'), ('INNOVATION', 'Innovation & Growth')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uom_type', models.CharField(choices=[('NUMERIC', 'Numeric (Higher is better)'), ('PERCENTAGE', 'Percentage (Higher is better)'), ('TIMELINE', 'Timeline (Date-based)'), ('ZERO', 'Zero-based (Zero = Success)')], max_length=20)),
                ('uom_direction', models.CharField(choices=[('MIN', 'Higher is better (Achievement ÷ Target)'), ('MAX', 'Lower is better (Target ÷ Achievement)')], default='MIN', max_length=10)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('weightage', models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('is_shared', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_goals', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
                ('shared_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_copies', to='app.goal')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.goal')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_checkins', to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quarterperiod')),
            ],
        ),
        migrations.CreateModel(
            name='SharedGoalDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('thrust_area', models.CharField(choices=[('SALES', 'Sales & Revenue'), ('CUSTOMER', 'Customer Success'), ('PRODUCT', 'Product Development'), ('OPERATIONS', 'Operations Excellence'), ('PEOPLE', 'People & Culture'), ('FINANCE', 'Financial Management'), ('COMPLIANCE', 'Compliance & Risk'), ('INNOVATION', 'Innovation & Growth')], max_length=50)),
                ('target_value', models.FloatField()),
                ('uom_type', models.CharField(choices=[('NUMERIC', 'Numeric (Higher is better)'), ('PERCENTAGE', 'Percentage (Higher is better)'), ('TIMELINE', 'Timeline (Date-based)'), ('ZERO', 'Zero-based (Zero = Success)')], max_length=20)),
                ('uom_direction', models.CharField(choices=[('MIN', 'Higher is better (Achievement ÷ Target)'), ('MAX', 'Lower is better (Target ÷ Achievement)')], default='MIN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('primary_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_shared_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedGoalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shared_goals', to=settings.AUTH_USER_MODEL)),
                ('goal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.goal')),
                ('shared_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.sharedgoaldefinition')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ON_TRACK', 'On Track'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='app.goal')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.quarterperiod')),
            ],
            options={
                'unique_together': {('goal', 'quarter')},
            },
        ),
    ]
